services:
  app:
    build: .
    container_name: card-app
    volumes:
      - .:/home/node/app
    networks:
      - card_app_net
    ports:
      - "3000:3000"

  db:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: card_app_db
    ports: 
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - card_app_net

volumes:
  pg_data:

networks:
  card_app_net: